name: "Build and Deploy development environment"

on:
  push:
    branches:
      - "development"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      keyvault_name: tripee-development
      environment: Development
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  deploy:
    name: "[DEV] Deploy"
    runs-on: ubuntu-latest
    needs: build
    environment: Development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # - name: Unzip artifact for deployment
      #   run: unzip ./release.zip -d ./deploy

      # - name: List deployment files
      #   run: ls -la ./deploy

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tripee-notification-api-dev'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
