name: "Build and Deploy staging environment"

on:
  push:
    branches:
      - "staging"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      keyvault_name: tripee-staging
      environment: Staging
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    environment: Staging

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tripee-notification-api-stg'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}