name: "Build and Deploy production environment"

on:
  push:
    branches:
      - "production"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      keyvault_name: tripee-production
      environment: Production
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    environment: Production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./artifact

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tripee-notification-api'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}